const express = require("express");
const router = express.Router();
const userRoutes = require("./user.route.js");
const roleRoutes = require("./role.route.js");
const categoryRoutes = require("./category.route.js");
const subCategoryRoutes = require("./subcategory.route.js");
const subjectRoutes = require("./subject.route.js");
const chapterRoutes = require("./chapter.route.js");
const lessonRoutes = require("./lesson.route.js");
const enrollmentRoutes = require("./enrollment.route.js");
const progressRoutes = require("./progress.route.js");
const subjectRatingRoutes = require("./subject-rating.route.js");
const lessonCommentRoutes = require("./lesson-comment.route.js");
const s3Routes = require("./s3.route.js");
const faq = require("./faq.route.js");
const subscribersRoutes = require("./subscribers.routes.js");
const testimonialsRoutes = require("./testimonial.route.js");
const helpRoutes = require("./help.route.js");
const pageRoutes = require("./page.route.js");

router.use("/users", userRoutes);
router.use("/roles", roleRoutes);
router.use("/categories", categoryRoutes);
router.use("/subcategories", subCategoryRoutes);
router.use("/subjects", subjectRoutes);
router.use("/chapters", chapterRoutes);
router.use("/lessons", lessonRoutes);
router.use("/enrollments", enrollmentRoutes);
router.use("/progress", progressRoutes);
router.use("/ratings", subjectRatingRoutes);
router.use("/lesson-comments", lessonCommentRoutes);
router.use("/s3", s3Routes);
router.use("/faq", faq);
router.use("/subscribers", subscribersRoutes);
router.use("/testimonial", testimonialsRoutes);
router.use("/help", helpRoutes);
router.use("/pages", pageRoutes);

module.exports = router;